
name: Validate Backwards Compability GraphQL Schema 
on: [push]
jobs:
  check-graphql-compability:
    name: Check Merged Schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          path: target
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install GraphQL inspector
        run: npm install --global @graphql-inspector/ci @graphql-inspector/diff-command @graphql-inspector/graphql-loader
      - name: Merge target schemas
        run: |
          cd target
          git branch
          cd schemas
          cut -b 1- ./*.graphql > schema.graphql
          # cat address.graphql person.graphql > schema.graphql
          cat schema.graphql
      - name: Checkout feature branch
        uses: actions/checkout@v2
        with:
          path: feature
      - name: Merge feature branch schemas
        run: |
          cd feature/schemas
          cut -b 1- ./*.graphql > schema.graphql
          # cat address.graphql person.graphql > schema.graphql
          cat schema.graphql
      - name: Compare merged schemas
        run: |
          graphql-inspector diff './target/schemas/schema.graphql' './feature/schemas/schema.graphql'