
name: Validate Backwards Compability GraphQL Schema 
on: [push]
jobs:
  # test:
  #   name: Check Schema
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@main
  #     - name: Check Address Schema
  #       uses: kamilkisiela/graphql-inspector@master
  #       with:
  #         schema: 'main:schemas/address.graphql'
  #     - name: Check Person Schema
  #       uses: kamilkisiela/graphql-inspector@master
  #       with:
  #         schema: 'main:schemas/person.graphql'
  test2:
    name: Check Merged Schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          path: target
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install GraphQL inspector ci
        run: npm install --global @graphql-inspector/ci
      - name: Install GraphQL inspector
        run: npm install --global @graphql-inspector/diff-command
      - name: Install GraphQL loader
        run: npm install --global @graphql-inspector/graphql-loader 
      - name: Merge target schemas
        run: |
          cd target/schemas
          cat address.graphql person.graphql > schema.graphql
          cat schema.graphql
      - name: Checkout feature branch
        uses: actions/checkout@v2
        with:
          path: feature
      - name: Merge feature branch schemas
        run: |
          cd feature/schemas
          cat address.graphql person.graphql > schema.graphql
          cat schema.graphql
      - name: Compare merged schemas
        run: |
          node -v
          ls
          graphql-inspector diff './target/schemas/schema.graphql' './feature/schemas/schema.graphql'
          ls
      # - name: Check Address Schema
      #   uses: kamilkisiela/graphql-inspector@master
      #   with:
      #     schema: 'target:schemas/address.graphql'
      # - name: Check Person Schema
      #   uses: kamilkisiela/graphql-inspector@master
      #   with:
      #     schema: 'main:schemas/person.graphql'