
name: Validate Backwards Compability GraphQL Schema 
on: [push]
jobs:
  check-graphql-compability:
    name: Check Merged Schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch
        uses: actions/checkout@main
        with:
          path: target
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install GraphQL inspector
        run: npm install --global @graphql-inspector/ci @graphql-inspector/diff-command @graphql-inspector/graphql-loader
      - name: Merge target schemas
        run: |
          cd target
          git fetch
          git checkout main
          cd schemas
          cut -b 1- ./*.graphql > schema.graphql
          cat schema.graphql
      - name: Checkout source branch
        uses: actions/checkout@v2
        with:
          path: source
      - name: Merge feature branch schemas
        run: |
          cd source/schemas
          cut -b 1- ./*.graphql > schema.graphql
          cat schema.graphql
      - name: Compare merged schemas
        run: |
          cat ./target/schemas/schema.graphql
          cat ./source/schemas/schema.graphql
          graphql-inspector diff './target/schemas/address.graphql' './source/schemas/address.graphql'